- name: Обновляем apt-кэш
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Устанавливаем нужные пакеты
  apt:
    name:
      - dante-server
      - libpam-pwdfile
    state: present

- name: Копируем конфиг Dante
  template:
    src: danted.conf.j2
    dest: /etc/danted.conf
    owner: root
    group: root
    mode: '0644'
  notify: Перезапустить danted

- name: Копируем PAM-конфиг для sockd
  template:
    src: pam_sockd.j2
    dest: /etc/pam.d/sockd
    owner: root
    group: root
    mode: '0644'
  notify: Перезапустить danted

- name: Создаём /etc/danted.passwd с пользователями
  copy:
    dest: /etc/danted.passwd
    content: |
      {% for user in users %}
      {{ user.name }}:{{ user.password }}
      {% endfor %}
    owner: proxy
    group: proxy
    mode: '0600'
  notify: Перезапустить danted

- name: Включаем и запускаем danted
  systemd:
    name: danted
    enabled: yes
    state: started
